[project]
name = "july-2025-multi-ai-agent-project"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "sympy>=1.0",
    "onnxruntime==1.22.0",
    "crewai==0.140.0",
    "crewai-tools==0.49.0",
    "docx2txt>=0.9",
    "llama-index==0.12.46",
    "llama-index-embeddings-huggingface==0.5.5",
    "llama-index-llms-groq==0.3.2",
    "llama-index-vector-stores-milvus==0.8.5",
    "groq==0.29.0",
    "langchain==0.3.26",
    "langchain-groq==0.3.5",
    "fastapi==0.115.14",
    "flagembedding>=1.3.5",
    "sentencepiece==0.2.0",
    "faiss-cpu>=1.11.0",
    "llama-index-vector-stores-faiss>=0.0.0",
    "llama-index-embeddings-cohere>=0.0.0",
    "llama-index-llms-openai==0.4.7",
    "langchain-community==0.3.27",
    "sentence-transformers==5.0.0",
    "openai==1.93.0",
    "llama-index-agent-openai==0.4.12",
    "llama-index-llms-cohere==0.5.0",
]